### ISSUE TITLE
DSSM default model fix

### ISSUE THREAD

**Issue by blondered** [MobileTeleSystems/RecTools#104]
### Feature Description

Right now DSSMModel has one parameter without the default value: `dataset_type: TorchDataset[tp.Any]`. This is very confusing since DSSMModel also has a default model. But user can't use it out of the box.

### Why this feature?

DSSMModel doesn't follow the simple interface from other RecTools models

**Comment by feldlime** [comment]
Closed with https://github.com/MobileTeleSystems/RecTools/pull/122
