### ISSUE TITLE
Add all models scores descriptions to docstrings

### ISSUE THREAD

**Issue by blondered** [MobileTeleSystems/RecTools#110]
### Feature Description

Extend models docstrings in the following way:
1. Add short description of the algorithm **if necessary** (examples of such short descriptions can be found in our README)
2. Add description to scores. For example, for ALS model it could be something like: `Model scores are dot products of learnt user embedding and recommended item embeddings for user-to-item recommendations. For item-to-item recommendations scores are cosine similarities between target item embedding and recommended item embeddings`.

### Why this feature?

Helpful for new users

**Comment by Saloni0512** [comment]
Hi, I would like to work on this issue, if it's still incomplete.

**Comment by blondered** [comment]
Hello! Sure, thanks.
I've extended description of this issue.
You can start from one model and open a draft PR with it. This way we can make sure that the form is right. And then you can continue to do descriptions to all of the models.

**Comment by Saloni0512** [comment]
Okay sure!

**Comment by Saloni0512** [comment]
Hi, I wanted to ask that in which file I am supposed to add the model scores . In the docs folder, there is a models.rst file and model_selection.rst file. Which one is supposed to have the required documentation.

**Comment by blondered** [comment]
Scores descriptions are supposed to be added to models docstrings in each module

**Comment by blondered** [comment]
I think, we are closing it since we are moving all this info to Extended Tutorial on RecSys Baselines. So it it now a duplicate

**Comment by Saloni0512** [comment]
Okay sure, is there something else I can contribute to @blondered

**Comment by blondered** [comment]
If you still want the same kind of issue (contributing to documentation) you can add links from each model class docstring to this model in our "Extended baselines tutorial": https://rectools.readthedocs.io/en/latest/examples/tutorials/baselines_extended_tutorial.html
Correct links for each model can be found on this page: https://rectools.readthedocs.io/en/latest/tutorials.html

It this ok for you?

**Comment by Saloni0512** [comment]
Yeah sure but under which issue will I work then I mean this one is closed so. @blondered
