### ISSUE TITLE
calc_metrics: Appropiate method for predicting for train / test? 

### ISSUE THREAD

**Issue by dataversenomad** [MobileTeleSystems/RecTools#146]
### Your Question

hi team. I was wondering what would be the correct way to predict for train (specifically) considering that I have trained the model.

dataset = dataset
top_k = 6

model = RandomModel()
model.fit(dataset)
recos = model.recommend(
                users=train_users,
                dataset=dataset,
                k=top_k,
                filter_viewed=True,
            )
metric_values = calc_metrics(metrics, recos, train, train, catalog)

**Is this the correct approach?**

it makes sense that for test should be:

recos = model.recommend(
                users=test_users,
                dataset=dataset,
                k=top_k,
                filter_viewed=True,
            )
metric_values = calc_metrics(metrics, recos, test, train, catalog)

I appreciate your help in advance.

### RecTools version

0.5.0

**Comment by dataversenomad** [comment]
it totally makes sense. I really appreciate all your help.

**Comment by feldlime** [comment]
Great, closing then
