### ISSUE TITLE
errore install [all]

### ISSUE THREAD

**Issue by TDL77** [MobileTeleSystems/RecTools#63]
pip install rectools и pip install rectools[extension-name]   установились нормально
а вот :
pip install rectools[all]  выдал вот такие ошибки ,
SDK и Visial Studio установлены !

        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_ext
      Extra compilation arguments: ['/EHsc', '/openmp', '/O2', '/DVERSION_INFO=\\"2.1.1\\"']
      building 'nmslib' extension
      creating build
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\similarity_search
      creating build\temp.win-amd64-cpython-310\Release\similarity_search\src
      creating build\temp.win-amd64-cpython-310\Release\similarity_search\src\method
      creating build\temp.win-amd64-cpython-310\Release\similarity_search\src\space
      creating build\temp.win-amd64-cpython-310\Release\tensorflow
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I.\similarity_search\include -Itensorflow -Ic:\temp\pip-install-b171phqx\nmslib_dde37a94bd0b4873a19978ddf40d8a69\.eggs\pybind11-2.6.1-py3.10.egg\pybind11\include -Ic:\temp\pip-install-b171phqx\nmslib_dde37a94bd0b4873a19978ddf40d8a69\.eggs\pybind11-2.6.1-py3.10.egg\pybind11\include -Ic:\temp\pip-install-b171phqx\nmslib_dde37a94bd0b4873a19978ddf40d8a69\.eggs\pybind11-2.6.1-py3.10.egg\pybind11\include -Ic:\temp\pip-install-b171phqx\nmslib_dde37a94bd0b4873a19978ddf40d8a69\.eggs\pybind11-2.6.1-py3.10.egg\pybind11\include -IC:\Users\TDL\mambaforge\envs\karp\lib\site-packages\numpy\core\include -IC:\Users\TDL\mambaforge\envs\karp\include -IC:\Users\TDL\mambaforge\envs\karp\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tp.\similarity_search\src\distcomp_bregman.cc /Fobuild\temp.win-amd64-cpython-310\Release\.\similarity_search\src\distcomp_bregman.obj /EHsc /openmp /O2 /DVERSION_INFO=\\\"2.1.1\\\"
      distcomp_bregman.cc
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: crtdbg.h: No such file or directory,
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib
ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects

**Comment by feldlime** [comment]
Seems like you have a problem with `nmslib` and you're using `Windows`. 
Have you tried to install `rectools[nmslib]`? I suppose no because there is no difference in installation process between installing`rectools[extension-name]` and `rectools[all]`.

Unfortunately, you cannot easily install `nmslib` on `Windows`. If you don't need it, then just list explicitly extras that you need like `rectools[torch,lightfm]`. If you really need `nmslib`, then try to use workarounds ([some ideas](https://stackoverflow.com/questions/57408679/how-can-i-install-nmslib-on-windows-10))

P.S. Next time specify your OS, Python version and provide specific commands that you're using. Also, use English, please.
